### PR TITLE
support ayatana-appindicator3 (libappindicator3 successor)

### PR DESCRIPTION
**Pull request by olback**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Documentation
- [x] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix: #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] A change file is added if any packages will require a version bump due to this PR per [the instructions in the readme](https://github.com/tauri-apps/tauri/blob/dev/.changes/readme.md).

If adding a **new feature**, the PR's description includes:
- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by amrbashir** [comment]
Why not just use https://github.com/emirror-de/libayatana-appindicator-rs ?

**Comment by olback** [comment]
> Why not just use https://github.com/emirror-de/libayatana-appindicator-rs ?

Because then libappindicator3 won't work.

Supporting both libayatana-appindicator and libappindicator makes this library work on almost any distro. For instance, Debian 11 does not ship libappindicator3 at all and instead suggests using libayatana-appindicator.

**Review by wusyong — APPROVED** [review]

**Comment by amrbashir** [comment]
@wusyong I really don't think merging this PR  waas the right move for a couple of  reasons:

1. `libayatana-appindicator` already had a rust crate which I linked above so this crate should only link to the old `libappindicator` so there isn't any confusion.
2. The problem which this PR tries to solve can't still be solved with this PR too. If I understand correctly, this PR will try to link **at compile time** to `libappindicator` and if it doesn't find it, it will try to link to `libayatana-appindicator` and that won't fix the issue on users end because If you compiled your app linking to `libayatana-appindicator` with this PR, users of your app will still have to install `libayatana-appindicator`. It doesn't detect the installed lib at runtime on users system and switches between the two libs accordingly.

The way I see it is someone could make another crate that detects at runtime the installed lib and then dynamically use the correct bindings for it. There is nothing wee should do on our end here.

**Comment by wusyong** [comment]
> at compile time
Ah I see the point. Let me revert a bit. I think for tauri, this would be the task for itself.
I was thinking maybe we can keep only one feature flag in tao but let's just remain the same and let tauri decide.

**Pull request merged**
